#cache line 32
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_cl_32_stats.txt gem5_results/parametroi_memonomena/bzip_cl_32_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_cl_32.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_cl_32_stats.txt gem5_results/parametroi_memonomena/hmmer_cl_32_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_cl_32.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_cl_32_stats.txt gem5_results/parametroi_memonomena/libm_cl_32_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_cl_32.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_cl_32_stats.txt gem5_results/parametroi_memonomena/mcf_cl_32_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_cl_32.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_cl_32_stats.txt gem5_results/parametroi_memonomena/sjeng_cl_32_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_cl_32.xml

#cache line 128
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_cl_128_stats.txt gem5_results/parametroi_memonomena/bzip_cl_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_cl_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_cl_128_stats.txt gem5_results/parametroi_memonomena/hmmer_cl_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_cl_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_cl_128_stats.txt gem5_results/parametroi_memonomena/libm_cl_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_cl_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_cl_128_stats.txt gem5_results/parametroi_memonomena/mcf_cl_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_cl_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_cl_128_stats.txt gem5_results/parametroi_memonomena/sjeng_cl_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_cl_128.xml

#L1 dcache assoc 4
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l1dassoc_4_stats.txt gem5_results/parametroi_memonomena/bzip_l1dassoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l1dassoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l1dassoc_4_stats.txt gem5_results/parametroi_memonomena/hmmer_l1dassoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l1dassoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l1dassoc_4_stats.txt gem5_results/parametroi_memonomena/libm_l1dassoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l1dassoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l1dassoc_4_stats.txt gem5_results/parametroi_memonomena/mcf_l1dassoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l1dassoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l1dassoc_4_stats.txt gem5_results/parametroi_memonomena/sjeng_l1dassoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l1dassoc_4.xml

#L1 dcache assoc 8
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l1dassoc_8_stats.txt gem5_results/parametroi_memonomena/bzip_l1dassoc_8_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l1dassoc_8.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l1dassoc_8_stats.txt gem5_results/parametroi_memonomena/hmmer_l1dassoc_8_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l1dassoc_8.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l1dassoc_8_stats.txt gem5_results/parametroi_memonomena/libm_l1dassoc_8_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l1dassoc_8.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l1dassoc_8_stats.txt gem5_results/parametroi_memonomena/mcf_l1dassoc_8_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l1dassoc_8.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l1dassoc_8_stats.txt gem5_results/parametroi_memonomena/sjeng_l1dassoc_8_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l1dassoc_8.xml

#L1d size 128
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l1dsize_128_stats.txt gem5_results/parametroi_memonomena/bzip_l1dsize_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l1dsize_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l1dsize_128_stats.txt gem5_results/parametroi_memonomena/hmmer_l1dsize_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l1dsize_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l1dsize_128_stats.txt gem5_results/parametroi_memonomena/libm_l1dsize_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l1dsize_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l1dsize_128_stats.txt gem5_results/parametroi_memonomena/mcf_l1dsize_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l1dsize_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l1dsize_128_stats.txt gem5_results/parametroi_memonomena/sjeng_l1dsize_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l1dsize_128.xml

#L1 icache assoc 4
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l1iassoc_4_stats.txt gem5_results/parametroi_memonomena/bzip_l1iassoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l1iassoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l1iassoc_4_stats.txt gem5_results/parametroi_memonomena/hmmer_l1iassoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l1iassoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l1iassoc_4_stats.txt gem5_results/parametroi_memonomena/libm_l1iassoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l1iassoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l1iassoc_4_stats.txt gem5_results/parametroi_memonomena/mcf_l1iassoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l1iassoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l1iassoc_4_stats.txt gem5_results/parametroi_memonomena/sjeng_l1iassoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l1iassoc_4.xml

#L1 icache assoc 8
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l1iassoc_8_stats.txt gem5_results/parametroi_memonomena/bzip_l1iassoc_8_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l1iassoc_8.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l1iassoc_8_stats.txt gem5_results/parametroi_memonomena/hmmer_l1iassoc_8_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l1iassoc_8.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l1iassoc_8_stats.txt gem5_results/parametroi_memonomena/libm_l1iassoc_8_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l1iassoc_8.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l1iassoc_8_stats.txt gem5_results/parametroi_memonomena/mcf_l1iassoc_8_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l1iassoc_8.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l1iassoc_8_stats.txt gem5_results/parametroi_memonomena/sjeng_l1iassoc_8_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l1iassoc_8.xml

#L1i size 64
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l1isize_64_stats.txt gem5_results/parametroi_memonomena/bzip_l1isize_64_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l1isize_64.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l1isize_64_stats.txt gem5_results/parametroi_memonomena/hmmer_l1isize_64_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l1isize_64.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l1isize_64_stats.txt gem5_results/parametroi_memonomena/libm_l1isize_64_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l1isize_64.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l1isize_64_stats.txt gem5_results/parametroi_memonomena/mcf_l1isize_64_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l1isize_64.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l1isize_64_stats.txt gem5_results/parametroi_memonomena/sjeng_l1isize_64_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l1isize_64.xml

#L1i size 128
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l1isize_128_stats.txt gem5_results/parametroi_memonomena/bzip_l1isize_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l1isize_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l1isize_128_stats.txt gem5_results/parametroi_memonomena/hmmer_l1isize_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l1isize_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l1isize_128_stats.txt gem5_results/parametroi_memonomena/libm_l1isize_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l1isize_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l1isize_128_stats.txt gem5_results/parametroi_memonomena/mcf_l1isize_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l1isize_128.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l1isize_128_stats.txt gem5_results/parametroi_memonomena/sjeng_l1isize_128_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l1isize_128.xml

#L2 cache assoc 4
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l2assoc_4_stats.txt gem5_results/parametroi_memonomena/bzip_l2assoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l2assoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l2assoc_4_stats.txt gem5_results/parametroi_memonomena/hmmer_l2assoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l2assoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l2assoc_4_stats.txt gem5_results/parametroi_memonomena/libm_l2assoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l2assoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l2assoc_4_stats.txt gem5_results/parametroi_memonomena/mcf_l2assoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l2assoc_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l2assoc_4_stats.txt gem5_results/parametroi_memonomena/sjeng_l2assoc_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l2assoc_4.xml

#L2 cache assoc 16
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l2assoc_16_stats.txt gem5_results/parametroi_memonomena/bzip_l2assoc_16_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l2assoc_16.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l2assoc_16_stats.txt gem5_results/parametroi_memonomena/hmmer_l2assoc_16_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l2assoc_16.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l2assoc_16_stats.txt gem5_results/parametroi_memonomena/libm_l2assoc_16_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l2assoc_16.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l2assoc_16_stats.txt gem5_results/parametroi_memonomena/mcf_l2assoc_16_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l2assoc_16.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l2assoc_16_stats.txt gem5_results/parametroi_memonomena/sjeng_l2assoc_16_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l2assoc_16.xml

#L2 size 1
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l2size_1_stats.txt gem5_results/parametroi_memonomena/bzip_l2size_1_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l2size_1.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l2size_1_stats.txt gem5_results/parametroi_memonomena/hmmer_l2size_1_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l2size_1.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l2size_1_stats.txt gem5_results/parametroi_memonomena/libm_l2size_1_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l2size_1.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l2size_1_stats.txt gem5_results/parametroi_memonomena/mcf_l2size_1_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l2size_1.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l2size_1_stats.txt gem5_results/parametroi_memonomena/sjeng_l2size_1_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l2size_1.xml

#L2 size 4
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l2size_4_stats.txt gem5_results/parametroi_memonomena/bzip_l2size_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l2size_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l2size_4_stats.txt gem5_results/parametroi_memonomena/hmmer_l2size_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l2size_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l2size_4_stats.txt gem5_results/parametroi_memonomena/libm_l2size_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l2size_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l2size_4_stats.txt gem5_results/parametroi_memonomena/mcf_l2size_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l2size_4.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l2size_4_stats.txt gem5_results/parametroi_memonomena/sjeng_l2size_4_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l2size_4.xml

#L2 size 512
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/bzip_l2size_512_stats.txt gem5_results/parametroi_memonomena/bzip_l2size_512_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/bzip_l2size_512.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/hmmer_l2size_512_stats.txt gem5_results/parametroi_memonomena/hmmer_l2size_512_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/hmmer_l2size_512.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/libm_l2size_512_stats.txt gem5_results/parametroi_memonomena/libm_l2size_512_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/libm_l2size_512.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/mcf_l2size_512_stats.txt gem5_results/parametroi_memonomena/mcf_l2size_512_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/mcf_l2size_512.xml
Scripts/GEM5ToMcPAT.py gem5_results/parametroi_memonomena/sjeng_l2size_512_stats.txt gem5_results/parametroi_memonomena/sjeng_l2size_512_config.json mcpat/ProcessorDescriptionFiles/inorder_arm.xml -o mcpat/vima_2_xml/parametroi_memonomena/sjeng_l2size_512.xml


